---
version: 2
formats: all
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - asdf plugin add poetry
    - asdf install poetry 1.6.1
    - asdf global poetry 1.6.1
    - poetry config virtualenvs.create false
    - poetry install --with docs
    - poetry run pdoc -d google -t pdoc-template --math -o _readthedocs/html/ arguebuf
    - cp -rf ./assets ./_readthedocs/html/
