---
# https://github.com/readthedocs/readthedocs.org/issues/4912
version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - epub
  - pdf
  - htmlzip

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
