---
# https://github.com/readthedocs/readthedocs.org/issues/4912
version: 2

mkdocs:
  configuration: mkdocs.yml

formats:
  - epub
  - pdf
  - htmlzip

python:
  version: "3.8"
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
