---
# https://github.com/readthedocs/readthedocs.org/issues/4912
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  # jobs:
  #   post_create_environment:
  #     - pip install poetry
  #     - poetry config virtualenvs.create false
  #   post_install:
  #     - poetry install --with docs
  commands:
    - pip install poetry==1.3.1
    - poetry config virtualenvs.create false
    - poetry install --with docs
    - poetry run pdoc -d google --math -o _readthedocs/html/ arguebuf

formats:
  - epub
  - pdf
  - htmlzip

python:
  version: "3.8"
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
