site_name: Arguebuf

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            merge_init_into_class: true
            show_if_no_docstring: true
            show_signature_annotations: true
            separate_signature: true
            members_order: source
