name: Format code with black

# https://github.com/stefanzweifel/git-auto-commit-action#workflow-should-run-in-base-repository
# https://github.com/stefanzweifel/git-auto-commit-action/issues/211

on:
  pull_request_target:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.head_ref }}
    - uses: psf/black@stable
      with:
        options: ""
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Enforce black code style
