on:
  pull_request:
  push:
    branches:
      - main
      - beta
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{ secrets.GH_PULL_CREDENTIALS }}
      - uses: actions/checkout@v3
      - uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "git@github.com:"
          replace: "https://github.com/"
          regex: false
          include: "**/*.dvc"
      - uses: iterative/setup-dvc@v1
        with:
          version: 2.55.0
      - uses: JRMurr/direnv-nix-action@v4.1.0
        with:
          cache-store: "false"
      - run: dvc pull --force --verbose
      - run: poetry run python -m pytest
  release:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.repository_owner == 'recap-utr' && github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3
      - uses: JRMurr/direnv-nix-action@v4.1.0
        with:
          cache-store: "false"
      - uses: cihelper/action-semanticrelease-poetry@v1
        id: semanticrelease
      - uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ steps.semanticrelease.outputs.released == 'true' }}
