on:
  push:
    branches:
      - main
      - beta
env:
  POETRY_VERSION: 1.3.1
  PYTHON_VERSION: 3.9
  DVC_VERSION: 2.43.0
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - uses: de-vri-es/setup-git-credentials@v2
      #   with:
      #     credentials: https://${{ secrets.GH_PULL_ACTOR }}:${{ secrets.GH_PULL_TOKEN }}@github.com/
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_ARGUEBASE_PUBLIC }}
            ${{ secrets.SSH_ARGUEBASE_PRIVATE }}
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: iterative/setup-dvc@v1
        with:
          version: ${{ env.DVC_VERSION }}
      - run: dvc pull --force --verbose
      - run: pip install poetry==${{ env.POETRY_VERSION }}
      - run: poetry config virtualenvs.in-project true
      - run: poetry install
      - run: poetry run pytest
  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: cihelper/action-semanticrelease-poetry@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          poetry-version: ${{ env.POETRY_VERSION }}
          pypi-token: ${{ secrets.PYPI_TOKEN }}
