on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: cihelper/action-semanticrelease-poetry@v1
        with:
          python-version: 3.9
          poetry-version: 1.3.1
          pypi-token: ${{ secrets.PYPI_TOKEN }}
